# Generated by Django 4.2.7 on 2023-11-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name_plural': 'Catalago_producto'},
        ),
    ]
