# Generated by Django 4.2.7 on 2023-12-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name_plural': 'Catalago_producto'},
        ),
    ]
