# Generated by Django 4.2.7 on 2023-12-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Catalogo_categoria',
        ),
    ]
