# Generated by Django 4.2.7 on 2023-12-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name_plural': 'Catalago_productoNuevos'},
        ),
    ]
