# Generated by Django 4.2.6 on 2023-11-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='', upload_to='categorias/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('N', 'Nuevo'), ('M', 'Mas Vendido'), ('O', 'Ofertas'), ('L', 'Liquidacion'), ('I', 'Inventario')], default='Nuevo', max_length=15)),
                ('presentacion', models.CharField(choices=[('1', 'Botella'), ('2', 'Caja'), ('3', 'Paquete'), ('4', 'Regalo')], default='Botella', max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('existencia', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Prodcutos',
            },
        ),
    ]
