# Generated by Django 4.2.7 on 2023-11-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField(blank=True, default='Descripcion...', null=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'db_table': 'Catalogo_categoria',
                'managed': False,
            },
        ),
    ]
